units:
  px: cx + 2
  py: cy + 2

  pushX: (cx / 2)
  pushY: (cy / 2)

  padX: pushX + 2
  padY: pushY + 2

  pad: 2
  spacing: 0.75
  controllerW: 18.5
  controllerH: 33.5
  belowControllerH: 17
  caseBorder: 1.5
  screwThreadRadius: 0.5
  screwPCBRadius: 4.0

points:
  zones:
    matrix:
      columns:
        outer:
          rows.bottom.skip: true
          key:
            column_net: P020 # top of nn
        pinky:
          key:
            column_net: P022 # top of nn
        ring:
          key:
            stagger: 9
            column_net: P024 # top of nn
        middle:
          key:
            stagger: 4
            column_net: P100 # top of nn
        index:
          key:
            stagger: -10
            column_net: P011 # top of nn
        inner:
          key:
            column_net: P017 # top of nn
      rows:
        bottom:
          row_net: P002 # bottom of nn
        home:
          row_net: P029 # bottom of nn
        top:
          row_net: P031 # bottom of nn
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-24, -20]
      columns:
        near:
          key:
            column_net: P100 # top of nn
        home:
          key:
            spread: 21.25
            splay: -12
            origin: [-11.75, -9]
            column_net: P011 # top of nn
        far:
          key:
            spread: 21.25
            splay: -12
            origin: [-9.5, -9]
            column_net: P017 # top of nn
      rows:
        thumb:
          row_net: P115 # bottom of nn
  mirror:
    ref: matrix_pinky_home
    distance: 230

outlines:
  keys_left:
    - where: /^matrix_|^thumbfan_/
      what: rectangle
      size: [cx + 4.5, cy + 5]
      fillet: 2

  keys_right:
    - where: /^mirror_matrix_|^mirror_thumbfan_/
      what: rectangle
      size: [cx + 4.5, cy + 5]
      fillet: 2

  full_left:
    - where: /^matrix_|^thumbfan_/
      what: rectangle
      size: [cx + 4.5, cy + 5]
    - what: polygon
      points:
        - ref: matrix_index_bottom # tl
          shift: [-10.25, 0]
        - ref: matrix_inner_bottom # tr
          shift: [11.3, -11]
        - ref: thumbfan_home_thumb # mrl
          shift: [14, 11]
        - ref: thumbfan_far_thumb # mrr
          shift: [-5, 11]
        - ref: thumbfan_far_thumb # brr
          shift: [0, -9.6]
        - ref: thumbfan_home_thumb # brl
          shift: [10, -9.7]
        - ref: thumbfan_near_thumb # blr
          shift: [10, -9.7]
        - ref: thumbfan_near_thumb # bll
          shift: [-5.2, -9.7]
      operation: add
      fillet: 3

  full_right:
    - where: /^mirror_matrix_|^mirror_thumbfan_/
      what: rectangle
      size: [cx + 4.5, cy + 5]
    - what: polygon
      points:
        - ref: mirror_matrix_index_bottom # tl
          shift: [-10.25, 0]
        - ref: mirror_matrix_inner_bottom # tr
          shift: [11.3, -11]
        - ref: mirror_thumbfan_home_thumb # mrl
          shift: [14, 11]
        - ref: mirror_thumbfan_far_thumb # mrr
          shift: [-5, 11]
        - ref: mirror_thumbfan_far_thumb # brr
          shift: [0, -9.6]
        - ref: mirror_thumbfan_home_thumb # brl
          shift: [10, -9.7]
        - ref: mirror_thumbfan_near_thumb # blr
          shift: [10, -9.7]
        - ref: mirror_thumbfan_near_thumb # bll
          shift: [-5.2, -9.7]
      operation: add
      fillet: 3

  xl_board_left:
    - where: /^matrix_|^thumbfan_/
      what: rectangle
      size: [cx + 10, cy + 10.5]
    - what: polygon # thumb key correction
      points:
        - ref: matrix_index_bottom # tl
          shift: [-10.25, 0]
        - ref: matrix_inner_bottom # tr
          shift: [12.3, -9]
        - ref: thumbfan_home_thumb # mrl
          shift: [13.3, 12.4]
        - ref: thumbfan_far_thumb # mrr
          shift: [-5, 11]
        - ref: thumbfan_far_thumb # brr
          shift: [0, -9.6]
        - ref: thumbfan_home_thumb # brl
          shift: [10, -9.7]
        - ref: thumbfan_near_thumb # blr
          shift: [10, -9.7]
        - ref: thumbfan_near_thumb # bll
          shift: [-5.2, -9.7]
    - what: polygon # battery case correction
      points:
        - ref: matrix_middle_bottom # tl
          shift: [-1, 0]
        - ref: matrix_middle_bottom # bl
          shift: [-1, -45]
        - ref: matrix_middle_bottom # br
          shift: [40, -45]
        - ref: matrix_middle_bottom # tr
          shift: [40, 0]
      operation: add
      fillet: 3

  xl_board_right:
    - where: /^mirror_matrix_|^mirror_thumbfan_/
      what: rectangle
      size: [cx + 10, cy + 10.5]
    - what: polygon # thumb key correction
      points:
        - ref: mirror_matrix_index_bottom # tl
          shift: [-10.25, 0]
        - ref: mirror_matrix_inner_bottom # tr
          shift: [12.3, -9]
        - ref: mirror_thumbfan_home_thumb # mrl
          shift: [13.3, 12.4]
        - ref: mirror_thumbfan_far_thumb # mrr
          shift: [-5, 11]
        - ref: mirror_thumbfan_far_thumb # brr
          shift: [0, -9.6]
        - ref: mirror_thumbfan_home_thumb # brl
          shift: [10, -9.7]
        - ref: mirror_thumbfan_near_thumb # blr
          shift: [10, -9.7]
        - ref: mirror_thumbfan_near_thumb # bll
          shift: [-5.2, -9.7]
    - what: polygon # battery case correction
      points:
        - ref: mirror_matrix_middle_bottom # tl
          shift: [-1, 0]
        - ref: mirror_matrix_middle_bottom # bl
          shift: [-1, -45]
        - ref: mirror_matrix_middle_bottom # br
          shift: [40, -45]
        - ref: mirror_matrix_middle_bottom # tr
          shift: [40, 0]
      operation: add
      fillet: 3

  key_cut_left:
    - where: /^matrix_|^thumbfan_/
      what: rectangle
      size: [14, 14]
      fillet: 0

  key_cut_right:
    - where: /^mirror_matrix_|^mirror_thumbfan_/
      what: rectangle
      size: [14, 14]
      fillet: 0

  plate_outline_left:
    - name: xl_board_left
    - operation: subtract
      name: key_cut_left

  plate_outline_right:
    - name: xl_board_right
    - operation: subtract
      name: key_cut_right

cases:
  plate_case_left:
    - what: outline
      name: plate_outline_left
      extrude: 1.2

  bottom_case_left:
    - what: outline
      name: xl_board_right
      extrude: 1.2

  plate_case_right:
    - what: outline
      name: plate_outline_right
      extrude: 1.2

  bottom_case_right:
    - what: outline
      name: xl_board_left
      extrude: 1.2

pcbs:
  left:
    # left edge cuts
    outlines:
      main:
        outline: full_left
    footprints:
      # left switch hotswaps
      mx_hotswap:
        what: mx
        where: /^matrix_|^thumbfan_/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          rotate: 180
      # left nice nano
      nice_nano:
        what: nice_nano
        params:
          orientation: up
        where:
          ref: matrix_inner_top
          shift: [-8.5, -1.5]
          rotate: -180
      # left power switch
      power_switch:
        what: slider
        where:
          ref: matrix_inner_home
          shift: [8.5, 4.0]
          rotate: -90
        params:
          side: B
          from: pos
          to: RAW
      # left reset button
      horizontal_reset:
        what: EVQPUC
        where:
          ref: matrix_inner_home
          shift: [8.5, -8.5]
          rotate: -90.0
        params:
          side: B
          from: GND
          to: RST
      # left mounting holes
      hole_bottom_right:
        what: mountinghole
        where:
          ref: thumbfan_far_thumb
          shift: [-pushX - 2, pushY - 2]
      hole_bottom_left:
        what: mountinghole
        where:
          ref: matrix_pinky_bottom
          shift: [pushX, pushY + 2]
      hole_top_left:
        what: mountinghole
        where:
          ref: matrix_pinky_top
          shift: [-pushX, -pushY]
      hole_top_right:
        what: mountinghole
        where:
          ref: matrix_middle_top
          shift: [pushX, -pushY]
      hole_center:
        what: mountinghole
        where:
          ref: matrix_middle_bottom
          shift: [-pushX, pushY]
      # left battery connection
      battery_jack:
        what: jstph
        where:
          ref: matrix_middle_home
          shift: [-7, 5.5]
          rotate: 90
        params:
            side: B
            pos: pos
            neg: GND
      # left diodes
      # this is all the ones that work like they should
      diode_main:
        what: diode
        where: /^matrix_(?!(?:pinky_top|ring_bottom|middle_home|index_top|inner_top))|^thumbfan_/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-8.2, -3.5]
          rotate: 90
      # the non correct positioned diodes
      diode_pinky_top:
        what: diode
        where: matrix_pinky_top
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-8, -0.5]
          rotate: 90
      diode_ring_bottom:
        what: diode
        where: matrix_ring_bottom
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-8, -6]
          rotate: 90
      diode_middle_home:
        what: diode
        where: matrix_middle_home
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-8.2, -3]
          rotate: 90
      diode_index_top:
        what: diode
        where: matrix_index_top
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-8.2, -5.5]
          rotate: 90
      diode_inner_top:
        what: diode
        where: matrix_inner_top
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-8.2, -1.5]
          rotate: 90
      # write "pengo" on the 
      front_text: &text
        what: text
        where: &textWhere
            ref: matrix_middle_top
            shift: [-6.7, 5.5]
        params: &textParams
            text: pengo
            justify: left
            h_size: 3.0
            v_size: 3.0
            thickness: 0.4
  right:
    # right edge cuts
    outlines:
      main:
        outline: full_right
    footprints:
      # right switch hotswaps
      mx_hotswap:
        what: mx
        where: /^mirror_matrix_|^mirror_thumbfan_/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          rotate: -180
      # right nice nano
      nice_nano:
        what: nice_nano
        params:
          orientation: up
        where:
          ref: mirror_matrix_inner_top
          shift: [-8.5, -1.5]
      # right power switch
      power_switch:
        what: slider
        where:
          ref: mirror_matrix_inner_home
          shift: [8.5, 4.0]
          rotate: -90
        params:
          side: B
          from: pos
          to: RAW
      # right reset button
      horizontal_reset:
        what: EVQPUC
        where:
          ref: mirror_matrix_inner_home
          shift: [8.5, -8.5]
          rotate: -90.0
        params:
          side: B
          from: GND
          to: RST
      # right mounting holes
      hole_bottom_right:
        what: mountinghole
        where:
          ref: mirror_thumbfan_far_thumb
          shift: [-pushX - 2, pushY - 2]
      hole_bottom_left:
        what: mountinghole
        where:
          ref: mirror_matrix_pinky_bottom
          shift: [pushX, pushY + 2]
      hole_top_left:
        what: mountinghole
        where:
          ref: mirror_matrix_pinky_top
          shift: [-pushX, -pushY]
      hole_top_right:
        what: mountinghole
        where:
          ref: mirror_matrix_middle_top
          shift: [pushX, -pushY]
      hole_center:
        what: mountinghole
        where:
          ref: mirror_matrix_middle_bottom
          shift: [-pushX, pushY]
      # right battery connection
      battery_jack:
        what: jstph
        where:
          ref: mirror_matrix_middle_home
          shift: [-7, 5.5]
          rotate: 90
        params:
            side: B
            pos: pos
            neg: GND
      # right diodes
      # this is all the ones that work like they should
      diode_main:
        what: diode
        where: /^mirror_matrix_(?!(?:inner_top|inner_home|index_top|middle_top|ring_home|pinky_home|outer_top))|^mirror_thumbfan_/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [8.2, -3.5]
          rotate: 270
      # the non correct positioned diodes
      diode_inner_top:
        what: diode
        where: mirror_matrix_inner_top
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-10, -1.5]
          rotate: 270
      diode_inner_home:
        what: diode
        where: mirror_matrix_inner_home
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-3, -8.5]
          rotate: 180
      diode_index_top:
        what: diode
        where: mirror_matrix_index_top
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-6.8, -9.5]
          rotate: 270
      diode_middle_top:
        what: diode
        where: mirror_matrix_middle_top
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-3, -8.5]
          rotate: 180
      diode_ring_home:
        what: diode
        where: mirror_matrix_ring_home
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-3, -8.5]
          rotate: 180
      diode_pinky_home:
        what: diode
        where: mirror_matrix_pinky_home
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-3, -8.5]
          rotate: 180
      diode_outer_top:
        what: diode
        where: mirror_matrix_outer_top
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-3, -8.5]
          rotate: 180
      # write "pengo" on the 
      front_text: &text
        what: text
        where: &textWhere
            ref: mirror_matrix_middle_top
            shift: [6.7, 5.5]
        params: &textParams
            text: pengo
            justify: left
            h_size: 3.0
            v_size: 3.0
            thickness: 0.4